#!/usr/bin/env bash

# Put into the directory specified by core.hooksPath or just `.git/hooks/`
# Then symlink each hookname to this script
# Hooks go in `HOOKNAME.d/` e.g. `pre-commit.d/00-hook1`, order is (from the location of this script)
# - $GIT_DIR/hooks/HOOKNAME.d/*
# - $GIT_CUSTOM_HOOKS_DIR/HOOKNAME.d/*
# - ./HOOKNAME.d/*

set -eEu -o pipefail
shopt -s inherit_errexit

BOLD=$(echo -e "\x1b[1m")
RED=$(echo -e "\x1b[31m")
GREEN=$(echo -e "\x1b[32m")
YELLOW=$(echo -e "\x1b[33m")
MAGENTA=$(echo -e "\x1b[35m")
CYAN=$(echo -e "\x1b[36m")
RESET=$(echo -e "\x1b[0m")

# optional debug output by TRACE=1
[[ "${TRACE:-0}" == "1" ]] && set -o xtrace
IFS=$'\n\t'
PS4='+\t '

STDIN=$(cat)

[[ -n "${GIT_DIR:-}" ]] && git_dir="$GIT_DIR"
unset $(git rev-parse --local-env-vars || true)
GIT_DIR="$(git rev-parse --git-dir 2>/dev/null)" || GIT_DIR="$git_dir"
export GIT_DIR
[[ -n "${git_dir:-}" ]] && unset git_dir

declare -a HOOKDIRS
HOOKDIRS+=("$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")
[[ -n "${GIT_CUSTOM_HOOKS_DIR:-}" ]] && HOOKDIRS+=("$GIT_CUSTOM_HOOKS_DIR")
HOOKDIRS+=("$GIT_DIR/hooks")

HOOKNAME=$(basename "${BASH_SOURCE[0]}")

cat <<-EOF
${BOLD}${CYAN}### RUNNING ${HOOKNAME^^} HOOKS ${RESET}

EOF

declare -A TO_RUN

for dir in "${HOOKDIRS[@]}"; do
	hookdir="${dir}/${HOOKNAME}.d"
	if [[ -d "$hookdir" ]]; then
		for hook in "$hookdir"/*; do
			hookname="$(basename "$hook")"
			TO_RUN[$hookname]="$hook"
		done
	fi
done

declare -a FAILED=()
declare -a PASSED=()

while read -r hookname; do
	hookscript="${TO_RUN[$hookname]}"
	if [[ -f "$hookscript" && -x "$hookscript" ]]; then
		hookname="$hookscript"
		[[ "$hookname" =~ ^"$HOME"(/|$) ]] && hookname="~${hookname#$HOME}"
		exit_code=0
		echo "${BOLD}${MAGENTA}##### GITHOOK: ${hookname}${RESET}"
		echo "$STDIN" | "$hookscript" "$@" 2>&1 || exit_code=$?

		if [[ $exit_code -eq 0 ]]; then
			PASSED+=("$hookname")
			cat <<-EOF
			${BOLD}${GREEN}--- PASSED ---${RESET}

			EOF
		else
			FAILED+=("$hookname")
			cat <<-EOF
			${BOLD}${RED}--- FAILED ---${RESET}

			EOF
		fi
	fi
done < <(
	for key in "${!TO_RUN[@]}"; do
		echo "$key"
	done | sort
)

echo "${BOLD}${CYAN}### ${HOOKNAME^^} SUMMARY ${RESET}"

if [[ "${#PASSED[@]}" -gt 0 ]]; then
	echo "${BOLD}${GREEN}PASSED: ${#PASSED[@]}${RESET}"
fi

if [[ "${#FAILED[@]}" -gt 0 ]]; then
	echo "${BOLD}${RED}FAILED: ${#FAILED[@]}${RESET}"
	exit 1
fi

echo ""
