#!/usr/bin/env bash

BOLD=$(echo -e "\x1b[1m")
RED=$(echo -e "\x1b[31m")
RESET=$(echo -e "\x1b[0m")

if ! command -v gitleaks >/dev/null 2>&1; then
	cat <<- EOF
	${BOLD}It looks like you don't have ${RED}gitleaks${RESET}${BOLD} installed!${RESET}

	You have a hook installed that uses gitleaks to scan for
	accidentally committed secrets. You can install gitleaks by either
	using your package manager or downloading from github:

	    https://github.com/gitleaks/gitleaks/releases/latest

	EOF

	exit 1
fi

gitleaks git --pre-commit --redact --staged --verbose --no-banner || exit $?
