#!/usr/bin/env bash

RED="\e[31m"
GREEN="\e[32m"
RESET="\e[0m"

exit_code=0
output="$(git --no-pager diff --cached --check 2>&1)" || exit_code=$?

if [[ $exit_code -ne 0 ]]; then
	echo -e "${RED}Found issues in the diff:${RESET}"
	echo "$output"

	echo -e "\n${RED}Please fix issues before committing${RESET}"
	exit 1
else
	echo -e "${GREEN}Diff is clean${RESET}"
fi
