#!/usr/bin/env bash

RED=$(echo -e "\x1b[31m")
GREEN=$(echo -e "\x1b[32m")
RESET=$(echo -e "\x1b[0m")

if ! git verify-commit HEAD >/dev/null 2>&1; then
	cat <<-EOF
	${RED}Commit '$(git --no-pager log -1 --format=format:"%h %s" HEAD)' isn't signed${RESET}
	Please amend the commit to be signed:

	    git commit -S --amend

	EOF
else
	echo "${GREEN}Commit '$(git --no-pager log -1 --format=format:"%h %s" HEAD)' is signed${RESET}"
fi
