#!/usr/bin/env bash

if ! command -v gitleaks >/dev/null 2>&1; then
	echo -e "\e[1mIt looks like you don't have \e[31mgitleaks\e[0;1m installed!\e[0m"
	echo
	echo "You have a hook installed that uses gitleaks to scan for"
	echo "accidentally committed secrets. You can install gitleaks by either"
	echo "using your package manager or downloading from github:"
	echo
	echo "    https://github.com/gitleaks/gitleaks/releases/latest"
	echo

	exit 1
fi

gitleaks git --pre-commit --redact --staged --verbose || exit $?
