#!/usr/bin/env bash

BOLD="\e[1m"
RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
RESET="\e[0m"

CONFIG_FILE="$(git rev-parse --show-toplevel)/.commitlintrc"
COMMIT_MSG=$(head -n1 "$1")

if [[ ! -f "$CONFIG_FILE" ]]; then
	echo -e "${YELLOW}No config file found, skipping...${RESET}"

	exit 0
fi

source "$CONFIG_FILE"

MERGE_REGEX="([Mm]erge[ a-z-]* branch.*)"
REVERT_REGEX="([Rr]evert.*)"

TYPE_REGEX="($(IFS=\|; echo "${TYPES[*]}"))"
[[ ${#SCOPES[*]} -gt 0 ]] && SCOPE_REGEX="(\($(IFS=\|; echo "${SCOPES[*]}")\))?" || SCOPE_REGEX="(\([a-zA-Z0-9_\-]+\))?"
SUBJECT_REGEX=".{1,$SUBJECT_MAX}"

REGEX="^(${MERGE_REGEX}|${REVERT_REGEX}|${TYPE_REGEX}${SCOPE_REGEX}!?: ${SUBJECT_REGEX})"

if ! [[ $COMMIT_MSG =~ $REGEX ]]; then
	cat <<-EOF
	$(echo -e "${RED}Commit message does not conform to the configured standard${RESET}")

	Your commit messages: "${COMMIT_MSG}"

	Expected format: <type>(<scope>): <subject>

	Allowed types: ${TYPES[*]}
	Allowed scopes: $([[ ${#SCOPES[*]} -gt 0 ]] && echo "${SCOPES[*]}" || echo "ANY")
	Subject max length: ${SUBJECT_MAX}

	Learn more about conventional commits at:

	    https://www.conventionalcommits.org

	EOF

	exit 1
fi

echo -e "${GREEN}Commit message ok${RESET}"
