#!/usr/bin/env bash

BOLD=$(echo -e "\x1b[1m")
RED=$(echo -e "\x1b[31m")
GREEN=$(echo -e "\x1b[32m")
YELLOW=$(echo -e "\x1b[33m")
RESET=$(echo -e "\x1b[0m")

CONFIG_FILE="$(git rev-parse --show-toplevel)/.commitlintrc"
COMMIT_MSG=$(head -n1 "$1")

if [[ ! -f "$CONFIG_FILE" ]]; then
	echo "${YELLOW}No config file found, skipping...${RESET}"

	exit 2
fi

if [[ -z $COMMIT_MSG ]]; then
	echo "${YELLOW}Empty commit message, no need to lint...${RESET}"

	exit 2
fi

source "$CONFIG_FILE"

MERGE_REGEX="([Mm]erge[ a-z-]* branch.*)"
REVERT_REGEX="([Rr]evert.*)"
TYPE_REGEX="($(IFS=\|; echo "${TYPES[*]}"))"
[[ ${#SCOPES[*]} -gt 0 ]] && SCOPE_REGEX="(\(($(IFS=\|; echo "${SCOPES[*]}"))\))?" || SCOPE_REGEX="(\([a-zA-Z0-9_\-]+\))?"
SUBJECT_REGEX=".{1,$SUBJECT_MAX}"

REGEX="^(${MERGE_REGEX}|${REVERT_REGEX}|${TYPE_REGEX}${SCOPE_REGEX}!?: ${SUBJECT_REGEX})"

if ! [[ $COMMIT_MSG =~ $REGEX ]]; then
	cat <<-EOF
	echo "${REGEX}"
	${RED}Commit message does not conform to the configured standard${RESET}

	Your commit messages: "${COMMIT_MSG}"

	Expected format: <type>(<scope>): <subject>

	Allowed types: ${TYPES[*]}
	Allowed scopes: $([[ ${#SCOPES[*]} -gt 0 ]] && echo "${SCOPES[*]}" || echo "ANY")
	Subject max length: ${SUBJECT_MAX}

	Learn more about conventional commits at:

	    https://www.conventionalcommits.org

	EOF

	exit 1
fi

echo "${GREEN}Commit message ok${RESET}"
